version: '3.1'
services:
  ghost-app:
    # build: ./ghost
    image: ghost:1.21.3
    restart: always
    depends_on:
      - db
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - ghost-app
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    volumes:
      - D:/opt/ghost/data:/var/lib/mysql
    ports:
      - "13306:3306"
